language: r
cache: packages
warnings_are_errors: true
sudo: required
notifications:
  email:
    recipients:
      - christoph.sax@gmail.com
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
